# Pergunta 13

## Enunciado

Como é feita a avaliação da política para as artes?

* Análise dos resultados dos programas, ações e chamadas públicas
* O órgão não realiza avaliação da política para as artes
* Realização de pesquisas
* Reuniões periódicas com o setor (participação social)
* Não existe política para as artes
* Outra(s). Especifique:

Quem executou a avaliação da política para as artes no período de 2020 a 2023?

* Conselho, Fóruns e outros (participação social)
* Empresa contratada
* Observatório ou outra instituição pública externa ao organismo
* Setor(es) do próprio organismo
* Outra(s). Especifique:

## Explicação

Esta pergunta está dividida em duas partes:

Avaliação da política para as artes: Na primeira parte, você deverá informar como é realizada a avaliação da política pelo ente. Caso não exista uma política específica para as artes, ou se o órgão responsável não conduzir tal avaliação, selecione a alternativa que responde a essa realidade na lista de itens.

Responsáveis pela avaliação da política para as artes: A segunda parte visa identificar quem conduziu o processo de avaliação da política para as artes no período de 2020 a 2023. São oferecidas diferentes opções de responsáveis pela execução desse processo, e o respondente deverá selecionar a opção que considere mais adequada.

### Observações importantes

* É possível marcar mais de uma opção nas questões, caso seja pertinente, exceto para as alternativas "Não existe política para as artes" e "O órgão não realiza avaliação da política para as artes", que devem ser selecionadas isoladamente.
* Se você selecionar a opção "Outra(s)", por favor, descreva as informações de forma clara e concisa.

