# Pergunta 19

## Enunciado

Quais elos da rede produtiva das artes foram contemplados nos editais da LAB (2020/2021) que tinham como objeto as linguagens artísticas?

* Acesso
* Criação
* Difusão
* Formação
* Memória
* Pesquisa

## Explicação

Essa questão tem como objetivo identificar quais elos da rede produtiva das artes foram contemplados pelos editais da Lei Aldir Blanc (LAB) focados nas linguagens artísticas entre 2020 e 2021.

### Descrição das alternativas

**Acesso:** Refere-se à disponibilização das obras artísticas para o público. Isso pode incluir ações que facilitem a democratização do acesso, como a distribuição de ingressos, exibições gratuitas ou plataformas de difusão online.

**Criação:** Ações que contemplam o processo de construção de espetáculos, obras e similares, bem como a atualização ou renovação daqueles já criados, entre outros.


**Difusão:** Está relacionada à disseminação das obras já produzidas. Isso pode incluir a organização de eventos, exibições ou qualquer outro meio que possibilite a apresentação das produções artísticas a um público mais amplo.

**Formação:** Ações que utilizem a linguagem artística como instrumento de diálogo pedagógico para  transformação social e construção de cidadania ou que proponham o desenvolvimento e aperfeiçoamento dessas  linguagens artísticas, tais como: oficinas, webinários, workshops, cursos livres, palestras, laboratórios, conferências, entre outros.

**Memória:** Envolve a preservação, o registro e a memória das artes,  compreendendo ações de preservação, restauro e difusão de acervos de agentes artísticos, instituições ou espaços, com o intuito de promover sua conservação e/ou acesso público,
inclusive por meio de websites, exposições, criação de banco de dados, entre outros.

**Pesquisa:** Refere-se ao estudo e à investigação no campo das artes, inclusive sua interface com o ambiente digital e as novas tecnologias, podendo resultar em artigos, catálogos, podcasts, mapeamentos, publicações, construção de metodologias, ensaios, e ainda a promoção da troca de experiências por meio da imersão artística em processos criativos compartilhados ou da interação entre diferentes criadores e suas metodologias, contribuindo para o desenvolvimento de pesquisas no campo das artes
  
 


