# Termo de Consentimento Livre e Esclarecido do/a respondente, do/a profissional e da organização 

## Enunciado

Ressaltamos que a sua participação é voluntária, não havendo penalidades decorrentes de sua desistência a qualquer momento. Os dados coletados serão tratados sempre de forma agrupada, protegendo a identidade do/a respondente, do/a profissional e da organização, e será considerada a lei vigente sobre segurança e proteção de dados, a Lei Federal nº 13.709/2018, Lei Geral de Proteção de Dados (LGPD). Todos os dados serão armazenados e ficarão sob a responsabilidade do Observatório de Economia Criativa da Bahia, entidade sediada na Universidade Federal da Bahia. Ao prosseguir neste questionário, você declara ter lido e entendido todas as informações repassadas e indica que concorda em participar desta pesquisa. Além disso, suas respostas serão salvas, permitindo que você retome o preenchimento posteriormente, se necessário.


* ACEITO PARTICIPAR - Declaro minha ciência sobre os procedimentos desta pesquisa e minha condição voluntária de participante.
* Eu não concordo em participar.

## Explicação

### Consentimento Livre e Esclarecido

Ao participar da pesquisa, você declara ter lido e entendido todas as informações repassadas e concorda com os termos descritos acima. Ressaltamos que a sua participação é voluntária e você pode desistir a qualquer momento sem nenhum tipo de penalidade.

### Confidencialidade e Segurança dos Dados

Os seus dados serão coletados e armazenados de forma sigilosa e segura. A identidade do/a respondente, do/a profissional e da organização será protegida e os dados serão tratados apenas de forma agrupada, não permitindo a identificação individual.

### Responsabilidade pelos Dados

O Observatório de Economia Criativa da Bahia, entidade sediada na Universidade Federal da Bahia, é responsável pela coleta, armazenamento e tratamento dos dados coletados.

### Armazenamento dos Dados

Os seus dados serão armazenados em um ambiente seguro e controlado pelo Observatório de Economia Criativa da Bahia. O acesso aos dados será restrito a um número limitado de pessoas autorizadas.

### Respondendo à Pergunta

Agora que você está ciente de todos os aspectos da pesquisa, você pode responder à pergunta: 

**ACEITO PARTICIPAR - Declaro minha ciência sobre os procedimentos desta pesquisa e minha condição voluntária de participante.**

Ao clicar em "ACEITO PARTICIPAR", você estará confirmando sua participação na pesquisa e concordando com todos os termos descritos neste manual.

### Eu não concordo em participar

Ao clicar em "Não", você estará informando que não deseja participar da pesquisa.
